name: "CI"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: "Test (node 14)"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout Branch"
        uses: actions/checkout@v3

      - name: "Use Node.js 14"
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"

      - name: "Start MongoDB"
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: "5.0"

      - name: "Install Dependencies"
        run: npm install -g npm && npm install && npm run build
        continue-on-error: true

      - name: "Run Tests"
        run: npm test

  format:
    name: "Format (deno fmt)"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout Branch"
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Format with Deno
        id: deno-fmt
        run: deno fmt
      - name: Check for modified files
        id: git-check
        run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Format Bot'
          git config --global user.email 'format-bot@netsblox.org'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Fix code formatting"
          git push
